import { COLORS } from "@/constants/theme";
import { StyleSheet, Dimensions } from "react-native";

const { width, height } = Dimensions.get("window");
export const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: "#000",
    },
    camera: {
        flex: 1,
        width: "100%",
    },
    overlay: {
        flex: 1,
        backgroundColor: "rgba(0, 0, 0, 0.5)",
        justifyContent: "center",
        alignItems: "center",
    },
    qrBox: {
        width: 280,
        height: 280,
        position: "relative",
        borderWidth: 1,
        borderColor: "rgba(255, 255, 255, 0.2)",
    },
    qrCorner: {
        position: "absolute",
        width: 40,
        height: 40,
        borderColor: "#00FFAA",
        borderWidth: 4,
    },
    topLeft: {
        top: -4,
        left: -4,
        borderRightWidth: 0,
        borderBottomWidth: 0,
    },
    topRight: {
        top: -4,
        right: -4,
        borderLeftWidth: 0,
        borderBottomWidth: 0,
    },
    bottomLeft: {
        bottom: -4,
        left: -4,
        borderRightWidth: 0,
        borderTopWidth: 0,
    },
    bottomRight: {
        bottom: -4,
        right: -4,
        borderLeftWidth: 0,
        borderTopWidth: 0,
    },
    scanLine: {
        position: "absolute",
        left: 0,
        right: 0,
        height: 2,
        backgroundColor: "#00FFAA",
        opacity: 0.8,
    },
    text: {
        fontSize: 20,
        fontWeight: "600",
        color: "#fff",
        textAlign: "center",
        marginBottom: 20,
        fontFamily: "System",
    },
    button: {
        paddingVertical: 14,
        paddingHorizontal: 24,
        backgroundColor: "#007BFF",
        borderRadius: 12,
        marginTop: 12,
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.3,
        shadowRadius: 4,
        elevation: 4,
    },
    buttonOpen: {
        backgroundColor: "#34A853",
    },
    buttonClose: {
        backgroundColor: "#FF3D00",
    },
    buttonText: {
        color: "#fff",
        fontSize: 16,
        fontWeight: "600",
        textAlign: "center",
        fontFamily: "System",
    },
    modalView: {
        flex: 1,
        margin: 40,
        backgroundColor: "rgba(30, 30, 30, 0.95)",
        borderRadius: 24,
        padding: 40,
        alignItems: "center",
        justifyContent: "center",
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.4,
        shadowRadius: 8,
        elevation: 8,
    },
    modalText: {
        fontSize: 24,
        fontWeight: "700",
        color: "#fff",
        textAlign: "center",
        marginBottom: 20,
        fontFamily: "System",
    },
    barcodeText: {
        fontSize: 18,
        color: "#E0E0E0",
        textAlign: "center",
        marginBottom: 24,
        fontFamily: "System",
        paddingHorizontal: 10,
    },
});
